Add publish action
iota-community/iota-wiki-cli pull request #13
Opened 2022-01-28 21:40 UTC by jlvandenhout

I've set up an `iota-community` organization on npmjs. This should publish to both the npmjs registry and this repos package registry when a release tag is pushed.

2022-01-30 18:03 UTC, Dr-Electron commented on .github/workflows/publish.yaml
> +        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```suggestion
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

```

2022-01-30 18:04 UTC, Dr-Electron requested changes

2022-01-30 18:04 UTC, Dr-Electron commented on .github/workflows/publish.yaml
> +        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
Please add a new line :trollface:

2022-01-30 22:16 UTC, Dr-Electron approved these changes
Lgtm 🤔

2022-01-31 08:35 UTC, eike-hass requested changes
we should ignore the lib folder in the `.gitignore` since it will be build and pushed to the registries.

2022-01-31 08:41 UTC, eike-hass commented
I wonder what the correct workflow for a release is. Maybe:
0. make sure signed commits are enabled locally
1. run `npm version X.X.X`
2. push changes (including the new tag)
3. create GitHub release
4. profit

2022-01-31 08:44 UTC, eike-hass commented
@jlvandenhout could you resign your commits? Let me know if you need help with that 👍

2022-01-31 09:00 UTC, lucas-tortora approved these changes

2022-01-31 16:58 UTC, eike-hass commented
> @jlvandenhout could you resign your commits? Let me know if you need help with that 👍

resolved :)

2022-01-31 17:12 UTC, eike-hass commented
> I wonder what the correct workflow for a release is. Maybe:
> 
> 1. make sure signed commits are enabled locally
> 2. run `npm version X.X.X`
> 3. push changes (including the new tag)
> 4. create GitHub release
> 5. profit
> 
> If yes, let's put it in the Readme

Will document after the first successful release.

2022-01-31 17:13 UTC, merged